version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    target-branch: main
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: main
    schedule:
      interval: "monthly"
