name: CI
on:
  push:
    branches:
      - prod
      - main
  workflow_dispatch:

env:
  SQLX_OFFLINE: true

jobs:
  check:
    uses: ./.github/workflows/check.yml

  build:
    runs-on: ubuntu-latest
    needs: [check]
    strategy:
      fail-fast: true
      matrix:
        arch:
          - { rustc: aarch64, debian: arm64 }
          - { rustc: x86_64, debian: amd64 }
    steps:
      - name: Check out code into the proper directory
        uses: actions/checkout@v4

      - name: Install cargo
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.arch.rustc }}-unknown-linux-musl

      - name: Cache rust
        uses: Swatinem/rust-cache@v2

      - name: Download musl development toolchain for ${{ matrix.arch.rustc }}
        run: curl -fsSl https://musl.cc/${{ matrix.arch.rustc }}-linux-musl-cross.tgz --output ${{ matrix.arch.rustc }}-linux-musl-cross.tgz

      - name: Set up musl-${{ matrix.arch.rustc }} development toolchain
        run: tar -xvf ./${{ matrix.arch.rustc }}-linux-musl-cross.tgz

      - name: Build executables
        run: cargo b --release --target ${{ matrix.arch.rustc }}-unknown-linux-musl
        env:
          TARGET_CC: ${{ github.workspace }}/${{ matrix.arch.rustc }}-linux-musl-cross/bin/${{ matrix.arch.rustc }}-linux-musl-cc
          TARGET_AR: ${{ github.workspace }}/${{ matrix.arch.rustc }}-linux-musl-cross/bin/${{ matrix.arch.rustc }}-linux-musl-ar
          RUSTFLAGS: -C linker=${{ github.workspace }}/${{ matrix.arch.rustc }}-linux-musl-cross/bin/${{ matrix.arch.rustc }}-linux-musl-cc -C target-feature=+crt-static

      - name: Get package name
        run: echo CARGO_PKG_NAME=`cargo metadata --format-version 1 | jq -r '.resolve.root as $root | .packages[] | select(.id==$root) .name'` >> $GITHUB_ENV

      - name: Get package version
        run: echo CARGO_PKG_VERSION=`cargo metadata --format-version 1 | jq -r '.resolve.root as $root | .packages[] | select(.id==$root) .version'` >> $GITHUB_ENV

      - name: Get package authors
        run: echo CARGO_PKG_AUTHORS=`cargo metadata --format-version 1 | jq -r '.resolve.root as $root | .packages[] | select(.id==$root) .authors | join(" ")'` >> $GITHUB_ENV

      - name: Get package description
        run: echo CARGO_PKG_DESCRIPTION=`cargo metadata --format-version 1 | jq -r '.resolve.root as $root | .packages[] | select(.id==$root) .description'` >> $GITHUB_ENV

      - name: make folders git doesn't store
        run: mkdir -p ./packaging/apt/usr/bin/ && mkdir -p ./packaging/apt/DEBIAN/

      - name: Generate debian packaging controller
        run: |
          echo "
          Package: ${{ env.CARGO_PKG_NAME }}
          Version: ${{ env.CARGO_PKG_VERSION }}
          Maintainer: ${{ env.CARGO_PKG_AUTHORS }}
          Architecture: ${{ matrix.arch.debian }}
          Homepage: https://github.com/${{ github.repository }}
          Description: ${{ env.CARGO_PKG_DESCRIPTION }}" >> ./packaging/apt/DEBIAN/control

      - name: Copy executable for packaging
        run: cp ./target/${{ matrix.arch.rustc }}-unknown-linux-musl/release/${{ env.CARGO_PKG_NAME }} ./packaging/apt/usr/bin

      - name: Set deb filename
        run: echo "DEBFILE_NAME=${{ env.CARGO_PKG_NAME }}_${{ env.CARGO_PKG_VERSION }}-1_${{ matrix.arch.debian }}" >> $GITHUB_ENV

      - name: Rename debian file directory
        run: mv ./packaging/apt ./packaging/${{ env.DEBFILE_NAME }}

      - name: Build debfile with dpkg
        run: dpkg --build ./packaging/${{ env.DEBFILE_NAME }}

      - name: Upload executables
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch.rustc }}-executables
          path: |
            target/${{ matrix.arch.rustc }}-unknown-linux-musl/release/${{ env.CARGO_PKG_NAME }}

      - name: Upload debfiles to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch.rustc }}-deb
          path: |
            ./packaging/${{ env.DEBFILE_NAME }}.deb
